project:
  type: website
  output-dir: docs
  
website:
  google-analytics: G-PP012BY7MS
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Home page"
        contents:
           - index.qmd
      - section: "Publications"
        contents:
          - text: Articles 
            file: publications.qmd
          - text: Lecture Notes
            file: lecturenotes.qmd
          - text: Book  
          - file: books.qmd
     
      - section: "Teaching"
        contents:
          - teaching.qmd
         
format:
  html:
    theme: flatly
    css: styles.css
    toc: true



