project:
  title: Luc Rey-Bellet Home Page 
  type: website
  output-dir: docs
  resources: 
    - "html/Markov.html"
    - "html/Poisson.html"
    - "html/Martingale.html"
    - "html/Part1.html"
    - "html/Part2.html"
    - "html/Part3.html"
    - "html/Part4.html"
    - "pdf/Slides25-00.pdf"
    - "*.pdf"

website:
  google-analytics: G-PP012BY7MS
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: Home page
        file: index.qmd
      - section: "Publications"
        contents:
          - text: Articles 
            file: publications.qmd
          - text: Lecture Notes
            file: lecturenotes.qmd
      - section: "Current Teaching"
        contents:
          - text: Stat 315 (F25)
            file: Stat315-F25.qmd 
      - section: "Past Teaching"
        contents:    
          - text: Math 606 (S25)
            file: Math606-S25.qmd
          - text: Stat 315 (S25)
            file: Stat315-S25.qmd  
          - text: Math 605 (F24)
            file: Math605-F24.qmd
          - text: Stat 315 (S24)
            file: Stat315-S24.qmd
          - text: Math 606 (S24)
            file: Math606-S24.qmd
         
format:
  html:
    email-obfuscation: references
    theme: default
    css: styles.css
    toc: true



