project:
  type: website
  output-dir: docs
  
website:
  title: "Home page of Luc Rey-Bellet"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Publications"
        contents:
          - text: Articles 
            file: publications.qmd
          - text: Lecture Notes
            file: lecturenotes.qmd
          - text: Book  
          - file: books.qmd
     
      - section: "Teaching"
        contents:
          - teachging.qmd
      
      - about.qmd      
  
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



