project:
  title: Luc Rey-Bellet Home Page 
  type: website
  output-dir: docs
  
website:
  google-analytics: G-PP012BY7MS
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: Home page
        file: index.qmd
      - section: "Publications"
        contents:
          - text: Articles 
            file: publications.qmd
          - text: Lecture Notes
            file: lecturenotes.qmd
          - text: Book  
            file: books.qmd
     
      - section: "Teaching"
        contents:
          - text: Teaching
            file: teaching.qmd
         
format:
  html:
    email-obfuscation: references
    theme: default
    css: styles.css
    toc: true



