---
title: "Lecture Notes"
---

## Ergodic properties of Markov Processes 

These lectures notes on the ergodic properties of Markov processes (especially with stochastic differential equations in mind) and applications to statistical mechanics  were written at the occasion of  a summer school on Open Quantum Systems held in Grenoble in the (very hot) summer of 2003. 

 + [Ergodic properties of Markov Proceses](pdf/EMP.pdf)

 + [Open classical systems](pdf/OCP.pdf)




## Probability and stochastic processes graduate level class

The slides/lecture notes are used when teaching the graduate probability sequence Math 606/606.  They are permanently under construction.

The slides are produced using the reveal.js slides which are parts of Quarto  <https://quarto.org/> line of products.  


### Part 1: Probability   (html slides, version Fall 2024)

 + [Part 1: Warming Up](https://luc-umass.github.io/html/Part1.html) and <a class="reprint" href="pdf/Part1.pdf"> PDF Version</a>  

  + [Part 2: Probability measures and Expectation](https://luc-umass.github.io/html/Part2.html) and  <a class="reprint" href="pdf/Part2.pdf"> PDF Version</a> 

  + [Part 3: Measures on product spaces and conditional expectation](https://luc-umass.github.io/html/Part3.html) and <a class="reprint" href="pdf/Part3.pdf"> PDF Version</a>  

  + [Part 4: Convergence of random variables and limit theorems](https://luc-umass.github.io/html/Part4.html) and <a class="reprint" href="pdf/Part4.pdf"> PDF Version</a>  

### Part 2: Stochastic Processes (html slides, version Spring 2025) 

+ [Part1:  Markov chains](https://luc-umass.github.io/html/Markov.html) and <a class="reprint" href="pdf/Markov.pdf"> PDF Version</a>  

+ [Part2 : Poisson processes and continuous time Markov chains](https://luc-umass.github.io/html/Poisson.html) and <a class="reprint" href="pdf/Poisson.pdf"> PDF Version</a>  

+ [Part3 :Martingales](https://luc-umass.github.io/html/Martingale.html) and <a class="reprint" href="pdf/Martingale.pdf"> PDF Version</a>  

