---
title: "Syllabus Math 605, Fall 2024"
subtitle: "Probability theory"
author: "Luc Rey-Bellet"
institute: "University of Massachusetts Amherst"
format:
  pdf:
    toc: false
    number-sections: false
    colorlinks: true
  html:
    toc: false
    html-math-method: katex
---

##  Instructor 

Luc Rey-Bellet  
LGRT 1423K  
<luc@math.umass.edu>  

## Office hours:  

 -  Tuesday 3:00 PM-4:00 PM in LGRT 1423 K or on [ZOOM](https://umass-amherst.zoom.us/my/luc.reybellet.office.hours)
 -  Friday 1:00 PM-2:00 in LGRT 1423 K or on [ZOOM](https://umass-amherst.zoom.us/my/luc.reybellet.office.hours)
 -  By appointment is always possible, and/or ask your questions be email.

## Class Meeting

Tu-Th, 11:30AM--12:45AM in LGRT 204


## Class homepage 

On Canvas at <https://umamherst.instructure.com/courses/22961>  



## Class slides

I will post class slides here. 

  + [Math 605 Fall 24: Part 1: Warming Up](https://luc-umass.github.io/html/Part1.html) and here is a <a class="reprint" href="pdf/Part1.pdf"> PDF Version</a>  

  + [Math 605 Fall 24: Part 2: Probability measures and Expectation](https://luc-umass.github.io/html/Part2.html) and here is a <a class="reprint" href="pdf/Part2.pdf"> PDF Version</a> 

In the meantime you can look at my slides from last year 

[Math 605 Fall 23 Probability slides](https://luc-umass.github.io/html/Probabilitymodels.html)


## Syllabus

This is the first part of a (newly renamed) 2-semester graduate sequence **Math605-Math606** which leads to the Stochastics qualifying exam. Prerequisites are 

1. a solid working knowledge of undergaduate probablilty (at least STAT 515 or STAT 607 or equivalent).
2. a  good working knowedge of analysis and proofs (at least Math 523 or equivalent) 
3. some mathematical maturity


### Learning Objectives  

One can do many interesting applications with undergaduate probability (i.e. probability without measure theory) but at some point one needs to up your game. The goal of the class is to bring your probability knowledge to the next level so that you can tackle more sophisticated problems and are able to take classes (or read by yourself) on, for exmaple,  stochastic processes, stochastic differential equations, statistical learning theory (an important component of machine learning), large deviation theory, optimal transport, information theory, ergodic theory and so on....        


In Math 605 we will cover some of the foundations of probability. 

1. What is a probability space and what are random variables? How do compute their distribution and how do we simulate them?
2. Conditional probability and independence.
2. Some background on measure and integration, and the $L^p$ spaces.
3. The mode of convergences of random variable, almost sure, in probabilty, in distribution.
4. Characteristic and Moment generating functions.
4. The limit theorems: Law of Large numbers and Centra Limit Theorem and Concentration inequalities. 
5. Conditional expectation, Martingale and Martingale convergence theorems.  


In Math 606 we will cover various aspects of stochastic processes.  One of the main goal in the class is to develop a "probabilist intuition and way of thinking". We will present some proofs and we will skip some others in order to provide a reasonably broad range of topics, concepts and techniques. We emphasize examples both in discrete and continuous time from a wide range of disciplines and with an eye on numerical implementation.  Among the topics treated in the class are


1. Discrete time Markov chains on discrete spaces. Definition and basic properties, classification of states (positive recurrence, recurrence and transience), stationary distribution and limit theorems, analysis of transient behavior, optimal stopping, Monte-Carlo Markov chains.
2. Continuous-Time Markov chains. Poisson Process, Birth and Death Process, and Queueing models. Renewal processes and semi-Markov processes.
3. Martingales and applications
4. Brownian motion and applications.


## Grade/assignment 

Weekly homework, one midterm and one final exam, each valued  1/3 of your grade. 

The homework can be found at the end of each section in the slides. It will be submitted via gradescope <https://www.gradescope.com/courses/829012>

##  Textbooks


The following text book 

*Probability Theory and Stochastic Processes* by Pierre Bremaud. Universitext. Springer 2020. ISBN: 978-3030401825

covers all the material in 605-606 (and more). My class is designed in a similar spirit and is at the same "intermediate" level. I think it is a really good book to learn 
the basic ides and concepts, and you can move on to more  comprehensive textbooks next (let's say the books by Durrett or Cinlar). 


There are many other excellent textbooks on probability theory, which are often more comprehensive than our textbook and cover more material 
and in more depth.  **I strongly encourage you to pick a book and read it in parallel to the class. This is a really important skill to learn for your future career.**
Ask me if you want some advice which one to pick.



1. *Probability: Theory and Examples* by Rick Durrett, 4th edition. Cambridge University Press  ISBN-13: 978-0521765398

1. *Probability and Stochastics*  by Erhan Cinlar. Graduate Texts in Mathematics 261.  Springer 2011

1. *Probability and Measure* by Patrick Billingsley. Wiley. 

1. *Probability Essentials* by Jean Jacod and Philip Protter, 2n edition. Universitext. Springer 2004. ISBN: 978-3-540-43871-7

1. *A first look at rigorous probability* by Jeffrey Rosenthal, 2n edition. World Scientific 2006
ISBN-10: 9812703713 ISBN-13: 978-9812703712
 
2. *A Probability Path* by Sidney Resnick. Birkhauser 2014

3. *Probability: Theory and Examples* by Rick Durrett, 4th edition. Cambridge University Press ISBN-10: 0521765390 ISBN-13: 978-0521765398

4. *Real Analysis and Probability* by R.M Dudley, 2nd edition. Cambridge University Press 2004

5. *Probability* by A. Shiryaev, 2nd edition. Springer 1995



Also for references here are the books recommended for Math 606  


1. *Markov Chains Gibbs Fields, Monte Carlo Simulation, and Queues*, 2nd edition (2007) by Pierre Bremaud, Springer.

1. *Introduction to Stochastic Processes*, 2nd edition (2007) by Gregory F. Lawler, Chapman&Hall.

1. *Adventures in Stochastic processes*, by Sidney I. Resnick, Birkhauser.

2. *Essentials of Stochastic Processes*, by Rick Durrett, Springer.

2. *Introduction to Probability Models*,  by Sheldon M. Ross, Academic Press

2. *Lectures on Monte-Carlo Methods*, by Neal N. Madras, American Mathematical Society

2. *Simulation and the Monte Carlo Method*, by Reuven Y. Rubinstein and Dirk P. Kroese , Wiley

2. *Markov chain and Mixing Times*, by David A. Levin, Yuval Peres, and Elizabeth L. Wilmer, American Mathematical Society

2. *Stochastic Processes*, by Sheldon M. Ross, Wiley.

2. *A first course in Stochastic Processes*, by Samuel Karlin and Howard M. Taylor, Academic Press.

##  Accommodation Statement

The University of Massachusetts Amherst is committed to making reasonable, effective and appropriate accommodations to meet the needs of students with disabilities and help
create a barrier-free campus. If you have a disability and require accommodations, please register with Disability Services (161 Whitmore Administration building; phone 413-545-0892) to have an accommodation letter sent to your faculty. Information on services and materials for registering are also available on their website <https://www.umass.edu/disability>. The University of Massachusetts Amherst is committed to providing an equal educational opportunity for all students. If you have a documented physical, psychological, or learning disability on file with Disability Services (DS), you may be eligible for reasonable academic accommodations to help you succeed in this
course. If you have a documented disability that requires an accommodation, please notify me within the first two weeks of the semester so that we may make appropriate arrangements. 

##  Title IX statement

In accordance with Title IX of the Education Amendments of 1972 that prohibits gender-based discrimination in educational settings that receive federal funds, the University of Massachusetts Amherst is committed to providing a safe learning environment for all students, free from all forms of discrimination, including sexual assault, sexual harassment, domestic violence, dating violence, stalking, and retaliation. This includes interactions in person or online through digital platforms and social media. Title IX also protects against discrimination on the basis of pregnancy, childbirth, false pregnancy, miscarriage, abortion, or related conditions, including recovery. There are resources here on campus to support you. A summary of the available Title IX resources (confidential and non-confidential) can be found at the following link: <https://www.umass.edu/titleix/resources>. You do not need to make a formal report to access them. If you need immediate support, you are not alone. Free and confidential support is available 24 hours a day / 7 days a week / 365 days a year at the SASA Hotline 413-545-0800.”
  

## Academic Honesty Statement:  
Since the integrity of the academic enterprise of any institution of higher education requires honesty in scholarship and research, academic honesty is required of all students at the University of Massachusetts Amherst. Academic dishonesty is prohibited in all programs of the University. Academic dishonesty includes but is not limited to: cheating, fabrication, plagiarism, and facilitating dishonesty. Appropriate sanctions may be imposed on any student who has committed an act
of academic dishonesty. Instructors should take reasonable steps to address academic misconduct. Any person who has reason to believe that a student has committed academic dishonesty should bring such information to the attention of the appropriate course instructor as soon as possible. Instances of academic dishonesty not related to a specific course should be brought to the attention of the appropriate department Head or Chair. Since students are expected to be familiar with this policy and the commonly accepted standards of academic integrity, ignorance of such standards is not normally sufficient evidence of lack of
intent <http://www.umass.edu/dean_students/codeofconduct/acadhonesty>.  